### ISSUE TITLE
Message : Network Error

### ISSUE THREAD

**Issue by itchenfei** [UISSH/frontend#5]
`{
  "message": "Network Error",
  "name": "Error",
  "stack": "Error: Network Error\n    at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n    at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:99:14)",
  "config": {
    "url": "/api/User/login/",
    "method": "post",
    "data": "{\"username\":\"root\",\"password\":\"root\"}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json"
    },
    "baseURL": "http://127.0.0.1:8000",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 600000,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    }
  }
}`

**Comment by itchenfei** [comment]
后台已经启动了，django的http://127.0.0.1:8000/api/User/login/测试正常

**Comment by zmaplex** [comment]
```bash
cd backend
cp .env.template .env
```
然后编辑 .env 把前端域名加入到 `CORS_ALLOWED_ORIGINS` 和 `CSRF_TRUSTED_ORIGINS` 中

https://github.com/UISSH/backend/blob/7e0facf3d39925aa5c20de7f04f82d58f782affc/.env.template#L29
```
CORS_ALLOWED_ORIGINS=http://localhost:8080,https://dev-dash.uissh.com,https://dash.uissh.com
CSRF_TRUSTED_ORIGINS=http://localhost:8080,https://dev-dash.uissh.com,https://dash.uissh.com
```
最后再启动 Django

**Comment by itchenfei** [comment]
我把所有的都加上了，还是不行，请教下是什么原因。。

CORS_ALLOWED_ORIGINS=http://localhost:8081,http://localhost:8080,http://localhost:8000,https://dev-dash.uissh.com,https://dash.uissh.com,http://10.0.8.8:8081,http://10.0.8.8:8080,http://10.0.8.8:8000,http://192.168.10.105:8081,http://192.168.10.105:8000,http://192.168.10.105:8080
CSRF_TRUSTED_ORIGINS=http://localhost:8081,http://localhost:8080,http://localhost:8000,https://dev-dash.uissh.com,https://dash.uissh.com,http://10.0.8.8:8081,http://10.0.8.8:8080,http://10.0.8.8:8000,http://192.168.10.105:8081,http://192.168.10.105:8000,http://192.168.10.105:8080

**Comment by itchenfei** [comment]
可以了，直接允许了Django的所有跨域请求，可以登录了，感谢~
